"""initial migration

Revision ID: 98e110f42c99
Revises: fd366e5efa8b
Create Date: 2017-02-15 17:18:37.352666

"""

# revision identifiers, used by Alembic.
revision = '98e110f42c99'
down_revision = 'fd366e5efa8b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('info', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    op.drop_column('users', 'info')
    # ### end Alembic commands ###
